### ISSUE TITLE
Plugins?

### ISSUE THREAD

**Issue by mathuin** [dlord/spigot-docker#3]
I really like your project, and I've already tweaked it to use screen instead of tmux and docker-compose to avoid long command lines and the like.  Once I figure out why using docker-compose keeps me from using screen (or tmux) -- something about a dumb terminal -- and thus breaking the console subcommand, I'll send you two pull requests.

That being said, the next step for me is to add plugins.  Do you have a plan or roadmap for supporting plugins?  My use case is to support my wife and MIL who have become accustomed to Essentials and Dynmap, so those would be required.  I could install them by hand, or even as additional RUN commands in the Dockerfile, but I was hoping you had a clever idea that would improve on this approach.

**Comment by dlord** [comment]
Hi @mathuin, thank you for your interest in this project. 

I highly recommend you check my Spigot Quickstart Project. I created that project to help people get started with using this Docker image. It also shows how to add plugins to the image by extending this image. 

The URL is https://github.com/dlord/spigot-docker-quickstart

The dumb terminal problem you're encountering can be solved by adding std_in and tty to your service definition in your Docker Compose file. That's the equivalent of the -it flag when executing docker run.

I have documented this project as thoroughly as I can. If there's something vague about it, please let me know, and I'll improve on it. If you have any questions about it, just let me know and I'll explain further.

**Comment by mathuin** [comment]
Your explanation was exactly what I needed, and I appreciate the quickstart!
