### ISSUE TITLE
Console command issue

### ISSUE THREAD

**Issue by wiput1999** [dlord/spigot-docker#5]
Hi I have an issue when try to run command into container
`docker exec spigot-instance spigot console say hello everybody!`
like your example I got
`Console command not supported on a dumb term.`
Why happen like this?

**Comment by wiput1999** [comment]
Are you still maintain this repository?

**Comment by dlord** [comment]
I think the instructions I provided are very clear on how to use this.

From the last paragraph of https://github.com/dlord/spigot-docker#starting-an-instance

>It is highly preferred to start the container with -it. This is needed in order to allow executing console commands via docker exec. This also allows Spigot to safely shutdown when stopping the container via docker stop. See the Scripting section for more details.

And I even gave an example of how to start this:

    docker run \
        --name spigot-instance \
        -p 0.0.0.0:25565:25565 \
        -d \
        -it \
        -e DEFAULT_OP=dinnerbone \
        -e MINECRAFT_EULA=true \
        dlord/spigot


Also mentioned here in https://github.com/dlord/spigot-docker#scripting

>This feature can be enabled by pasing the -it parameter to docker create or docker run, which enables STDIN and TTY. This runs the Spigot server inside a tmux session. This also enables safe shutdown mode when the container is stopped.

I assume you have basic knowledge on how to use Docker.

I do keep track of any major issues, but I'm too busy with work. Feel free to fork it if necessary.

**Comment by mixxit** [comment]
How are we supposed to do this inside cron?

**Comment by ProgrammAbel** [comment]
Hi, I've passed the `-it` parameter but it still comes up with this message, does anything else need to be done?
